// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this project by running a command like:\n'
        '\'flutterfire configure --web-renderer html-renderer\'',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this project by running a command like:\n'
          '\'flutterfire configure --macos-bundle-id com.example.my-app\'',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this project by running a command like:\n'
          '\'flutterfire configure --windows-app-id com.example.my-app\'',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this project by running a command like:\n'
          '\'flutterfire configure --linux-app-id com.example.my-app\'',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxf2p9xxPUeWTT6K2a9sGfRaTOxXi3jE',
    appId: '1:591237109795:android:12c9590509a232179d7996',
    messagingSenderId: '591237109795',
    projectId: 'location-tracking-app-d1754',
    storageBucket: 'location-tracking-app-d1754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // This will be populated for you
    appId: 'com.finesoft.location_tracking_app', // This will be populated for you
    messagingSenderId: '591237109795',
    projectId: 'location-tracking-app-d1754',
    storageBucket: 'location-tracking-app-d1754.appspot.com',
    iosBundleId: 'com.finesoft.location_tracking_app',
  );
}